// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/statsservice.proto

package go_micro_srv_statsservice

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetPlayerStatsRequest struct {
	PlayerId             string   `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	SeasonId             int32    `protobuf:"varint,2,opt,name=season_id,json=seasonId,proto3" json:"season_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPlayerStatsRequest) Reset()         { *m = GetPlayerStatsRequest{} }
func (m *GetPlayerStatsRequest) String() string { return proto.CompactTextString(m) }
func (*GetPlayerStatsRequest) ProtoMessage()    {}
func (*GetPlayerStatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_statsservice_e1784bb03c36e533, []int{0}
}
func (m *GetPlayerStatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPlayerStatsRequest.Unmarshal(m, b)
}
func (m *GetPlayerStatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPlayerStatsRequest.Marshal(b, m, deterministic)
}
func (dst *GetPlayerStatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlayerStatsRequest.Merge(dst, src)
}
func (m *GetPlayerStatsRequest) XXX_Size() int {
	return xxx_messageInfo_GetPlayerStatsRequest.Size(m)
}
func (m *GetPlayerStatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlayerStatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlayerStatsRequest proto.InternalMessageInfo

func (m *GetPlayerStatsRequest) GetPlayerId() string {
	if m != nil {
		return m.PlayerId
	}
	return ""
}

func (m *GetPlayerStatsRequest) GetSeasonId() int32 {
	if m != nil {
		return m.SeasonId
	}
	return 0
}

type BaseStatsResponse struct {
	Stats                *BaseStats `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *BaseStatsResponse) Reset()         { *m = BaseStatsResponse{} }
func (m *BaseStatsResponse) String() string { return proto.CompactTextString(m) }
func (*BaseStatsResponse) ProtoMessage()    {}
func (*BaseStatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_statsservice_e1784bb03c36e533, []int{1}
}
func (m *BaseStatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseStatsResponse.Unmarshal(m, b)
}
func (m *BaseStatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseStatsResponse.Marshal(b, m, deterministic)
}
func (dst *BaseStatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseStatsResponse.Merge(dst, src)
}
func (m *BaseStatsResponse) XXX_Size() int {
	return xxx_messageInfo_BaseStatsResponse.Size(m)
}
func (m *BaseStatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseStatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BaseStatsResponse proto.InternalMessageInfo

func (m *BaseStatsResponse) GetStats() *BaseStats {
	if m != nil {
		return m.Stats
	}
	return nil
}

// Note I will do a pull from the api if no entry in the db exists, and then insert it in my db so that I can modify the data
// How to handle the fact that different positions have different stats?
// Note player id and season id can probably be a composite key in this case
type BaseStats struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PlayerId             string   `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Season               int32    `protobuf:"varint,3,opt,name=season,proto3" json:"season,omitempty"`
	GamesPlayed          int32    `protobuf:"varint,4,opt,name=games_played,json=gamesPlayed,proto3" json:"games_played,omitempty"`
	GamesStarted         int32    `protobuf:"varint,5,opt,name=games_started,json=gamesStarted,proto3" json:"games_started,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseStats) Reset()         { *m = BaseStats{} }
func (m *BaseStats) String() string { return proto.CompactTextString(m) }
func (*BaseStats) ProtoMessage()    {}
func (*BaseStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_statsservice_e1784bb03c36e533, []int{2}
}
func (m *BaseStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseStats.Unmarshal(m, b)
}
func (m *BaseStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseStats.Marshal(b, m, deterministic)
}
func (dst *BaseStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseStats.Merge(dst, src)
}
func (m *BaseStats) XXX_Size() int {
	return xxx_messageInfo_BaseStats.Size(m)
}
func (m *BaseStats) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseStats.DiscardUnknown(m)
}

var xxx_messageInfo_BaseStats proto.InternalMessageInfo

func (m *BaseStats) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *BaseStats) GetPlayerId() string {
	if m != nil {
		return m.PlayerId
	}
	return ""
}

func (m *BaseStats) GetSeason() int32 {
	if m != nil {
		return m.Season
	}
	return 0
}

func (m *BaseStats) GetGamesPlayed() int32 {
	if m != nil {
		return m.GamesPlayed
	}
	return 0
}

func (m *BaseStats) GetGamesStarted() int32 {
	if m != nil {
		return m.GamesStarted
	}
	return 0
}

type PassingStates struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PassingStates) Reset()         { *m = PassingStates{} }
func (m *PassingStates) String() string { return proto.CompactTextString(m) }
func (*PassingStates) ProtoMessage()    {}
func (*PassingStates) Descriptor() ([]byte, []int) {
	return fileDescriptor_statsservice_e1784bb03c36e533, []int{3}
}
func (m *PassingStates) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PassingStates.Unmarshal(m, b)
}
func (m *PassingStates) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PassingStates.Marshal(b, m, deterministic)
}
func (dst *PassingStates) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PassingStates.Merge(dst, src)
}
func (m *PassingStates) XXX_Size() int {
	return xxx_messageInfo_PassingStates.Size(m)
}
func (m *PassingStates) XXX_DiscardUnknown() {
	xxx_messageInfo_PassingStates.DiscardUnknown(m)
}

var xxx_messageInfo_PassingStates proto.InternalMessageInfo

type RushingStats struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RushingStats) Reset()         { *m = RushingStats{} }
func (m *RushingStats) String() string { return proto.CompactTextString(m) }
func (*RushingStats) ProtoMessage()    {}
func (*RushingStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_statsservice_e1784bb03c36e533, []int{4}
}
func (m *RushingStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RushingStats.Unmarshal(m, b)
}
func (m *RushingStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RushingStats.Marshal(b, m, deterministic)
}
func (dst *RushingStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RushingStats.Merge(dst, src)
}
func (m *RushingStats) XXX_Size() int {
	return xxx_messageInfo_RushingStats.Size(m)
}
func (m *RushingStats) XXX_DiscardUnknown() {
	xxx_messageInfo_RushingStats.DiscardUnknown(m)
}

var xxx_messageInfo_RushingStats proto.InternalMessageInfo

type RecievingStats struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecievingStats) Reset()         { *m = RecievingStats{} }
func (m *RecievingStats) String() string { return proto.CompactTextString(m) }
func (*RecievingStats) ProtoMessage()    {}
func (*RecievingStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_statsservice_e1784bb03c36e533, []int{5}
}
func (m *RecievingStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecievingStats.Unmarshal(m, b)
}
func (m *RecievingStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecievingStats.Marshal(b, m, deterministic)
}
func (dst *RecievingStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecievingStats.Merge(dst, src)
}
func (m *RecievingStats) XXX_Size() int {
	return xxx_messageInfo_RecievingStats.Size(m)
}
func (m *RecievingStats) XXX_DiscardUnknown() {
	xxx_messageInfo_RecievingStats.DiscardUnknown(m)
}

var xxx_messageInfo_RecievingStats proto.InternalMessageInfo

type DefensiveStats struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DefensiveStats) Reset()         { *m = DefensiveStats{} }
func (m *DefensiveStats) String() string { return proto.CompactTextString(m) }
func (*DefensiveStats) ProtoMessage()    {}
func (*DefensiveStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_statsservice_e1784bb03c36e533, []int{6}
}
func (m *DefensiveStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DefensiveStats.Unmarshal(m, b)
}
func (m *DefensiveStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DefensiveStats.Marshal(b, m, deterministic)
}
func (dst *DefensiveStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DefensiveStats.Merge(dst, src)
}
func (m *DefensiveStats) XXX_Size() int {
	return xxx_messageInfo_DefensiveStats.Size(m)
}
func (m *DefensiveStats) XXX_DiscardUnknown() {
	xxx_messageInfo_DefensiveStats.DiscardUnknown(m)
}

var xxx_messageInfo_DefensiveStats proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GetPlayerStatsRequest)(nil), "go.micro.srv.statsservice.GetPlayerStatsRequest")
	proto.RegisterType((*BaseStatsResponse)(nil), "go.micro.srv.statsservice.BaseStatsResponse")
	proto.RegisterType((*BaseStats)(nil), "go.micro.srv.statsservice.BaseStats")
	proto.RegisterType((*PassingStates)(nil), "go.micro.srv.statsservice.PassingStates")
	proto.RegisterType((*RushingStats)(nil), "go.micro.srv.statsservice.RushingStats")
	proto.RegisterType((*RecievingStats)(nil), "go.micro.srv.statsservice.RecievingStats")
	proto.RegisterType((*DefensiveStats)(nil), "go.micro.srv.statsservice.DefensiveStats")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for StatsService service

type StatsServiceClient interface {
	GetPlayerBaseStats(ctx context.Context, in *GetPlayerStatsRequest, opts ...client.CallOption) (*BaseStatsResponse, error)
}

type statsServiceClient struct {
	c           client.Client
	serviceName string
}

func NewStatsServiceClient(serviceName string, c client.Client) StatsServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.statsservice"
	}
	return &statsServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *statsServiceClient) GetPlayerBaseStats(ctx context.Context, in *GetPlayerStatsRequest, opts ...client.CallOption) (*BaseStatsResponse, error) {
	req := c.c.NewRequest(c.serviceName, "StatsService.GetPlayerBaseStats", in)
	out := new(BaseStatsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for StatsService service

type StatsServiceHandler interface {
	GetPlayerBaseStats(context.Context, *GetPlayerStatsRequest, *BaseStatsResponse) error
}

func RegisterStatsServiceHandler(s server.Server, hdlr StatsServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&StatsService{hdlr}, opts...))
}

type StatsService struct {
	StatsServiceHandler
}

func (h *StatsService) GetPlayerBaseStats(ctx context.Context, in *GetPlayerStatsRequest, out *BaseStatsResponse) error {
	return h.StatsServiceHandler.GetPlayerBaseStats(ctx, in, out)
}

func init() {
	proto.RegisterFile("proto/statsservice.proto", fileDescriptor_statsservice_e1784bb03c36e533)
}

var fileDescriptor_statsservice_e1784bb03c36e533 = []byte{
	// 318 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4f, 0x4e, 0xf3, 0x30,
	0x10, 0xc5, 0xbf, 0xe4, 0xa3, 0x55, 0x3b, 0xfd, 0x03, 0x58, 0x02, 0x05, 0xd8, 0x14, 0xc3, 0xa2,
	0x0b, 0x14, 0x50, 0xd9, 0xb1, 0x44, 0x48, 0xa8, 0x2b, 0x4a, 0x7a, 0x80, 0xca, 0xd4, 0x43, 0xb1,
	0x44, 0xe3, 0xe2, 0x71, 0x23, 0x71, 0x01, 0xce, 0xc0, 0x71, 0x51, 0xc6, 0x51, 0x5b, 0x10, 0x20,
	0x76, 0xc9, 0xef, 0xbd, 0x71, 0x9e, 0xdf, 0x04, 0x92, 0x85, 0xb3, 0xde, 0x9e, 0x93, 0x57, 0x9e,
	0x08, 0x5d, 0x61, 0xa6, 0x98, 0x32, 0x12, 0x07, 0x33, 0x9b, 0xce, 0xcd, 0xd4, 0xd9, 0x94, 0x5c,
	0x91, 0x6e, 0x1a, 0xe4, 0x3d, 0xec, 0xdd, 0xa2, 0x1f, 0x3d, 0xab, 0x57, 0x74, 0xe3, 0x52, 0xc8,
	0xf0, 0x65, 0x89, 0xe4, 0xc5, 0x11, 0x34, 0x17, 0x4c, 0x27, 0x46, 0x27, 0x51, 0x2f, 0xea, 0x37,
	0xb3, 0x46, 0x00, 0x43, 0x5d, 0x8a, 0x84, 0x8a, 0x6c, 0x5e, 0x8a, 0x71, 0x2f, 0xea, 0xd7, 0xb2,
	0x46, 0x00, 0x43, 0x2d, 0xef, 0x60, 0xf7, 0x5a, 0x11, 0x56, 0xa7, 0xd1, 0xc2, 0xe6, 0x84, 0xe2,
	0x0a, 0x6a, 0xfc, 0x5d, 0x3e, 0xaa, 0x35, 0x38, 0x4d, 0x7f, 0x8c, 0x94, 0xae, 0x87, 0xc3, 0x88,
	0x7c, 0x8f, 0xa0, 0xb9, 0x82, 0xa2, 0x0b, 0xf1, 0x2a, 0x51, 0x6c, 0xf4, 0xe7, 0xa0, 0xf1, 0x97,
	0xa0, 0xfb, 0x50, 0x0f, 0xb9, 0x92, 0xff, 0x9c, 0xb2, 0x7a, 0x13, 0xc7, 0xd0, 0x9e, 0xa9, 0x39,
	0xd2, 0x84, 0x9d, 0x3a, 0xd9, 0x62, 0xb5, 0xc5, 0x8c, 0xcb, 0xd0, 0xe2, 0x04, 0x3a, 0xc1, 0x42,
	0x5e, 0x39, 0x8f, 0x3a, 0xa9, 0xb1, 0x27, 0xcc, 0x8d, 0x03, 0x93, 0xdb, 0xd0, 0x19, 0x29, 0x22,
	0x93, 0xcf, 0xca, 0x70, 0x48, 0xb2, 0x0b, 0xed, 0x6c, 0x49, 0x4f, 0x15, 0x20, 0xb9, 0x03, 0xdd,
	0x0c, 0xa7, 0x06, 0x8b, 0x4d, 0x72, 0x83, 0x8f, 0x98, 0x93, 0x29, 0xc2, 0x8d, 0x06, 0x6f, 0x11,
	0xb4, 0xf9, 0x69, 0x1c, 0x1a, 0x10, 0x05, 0x88, 0xd5, 0x52, 0xd6, 0x17, 0xbf, 0xf8, 0xa5, 0xb3,
	0x6f, 0x77, 0x78, 0x78, 0xf6, 0xa7, 0x96, 0xab, 0x15, 0xc9, 0x7f, 0x0f, 0x75, 0xfe, 0x5d, 0x2e,
	0x3f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x5d, 0xfc, 0x1c, 0xca, 0x4a, 0x02, 0x00, 0x00,
}
